[#-- @ftlvariable name="deploymentResult" type="com.atlassian.bamboo.deployments.results.DeploymentResult" --]
[#-- @ftlvariable name="deploymentProject" type="com.atlassian.bamboo.deployments.projects.DeploymentProject" --]
[#-- @ftlvariable name="numFailures" type="Integer" --]
[#assign deployment=deploymentProject.name /]
[#assign release=deploymentResult.deploymentVersion.name /]
[#assign environment=deploymentResult.environment.name /]
${deployment} ${release}[#t]
[#if deploymentResult.deploymentState == "Successful"] was successfully deployed to ${environment} after ${numFailures} [#if numFailures = 1]failure[#else]failures[/#if].[#rt]
[#elseif deploymentResult.deploymentState == "Failed"] failed deploying to ${environment} (${numFailures} [#if numFailures = 1]times[#else]times[/#if]).[#rt]
[#else] stopped deploying to ${environment}[#rt]
[/#if]